module RbsConfig
  class RakeTask < Rake::TaskLib
    attr_accessor type: :config | :rails
    attr_accessor class_name: String
    attr_accessor files: Array[Pathname]
    attr_accessor name: Symbol
    attr_accessor mapping: Hash[untyped, Hash[untyped, untyped]]
    attr_accessor signature_root_dir: Pathname

    def initialize: (?Symbol name) ? { (RbsConfig::RakeTask) -> void } -> void

    def define_setup_task: () -> void
    def define_generate_task: () -> void
    def define_clean_task: () -> void
  end
end
